name: Python Tests

on:
  push:
    paths:
      - "**.py"
      - "tests/**"
  pull_request:
    paths:
      - "**.py"
      - "tests/**"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIPS_ATLAS_CONFIG: ${{ secrets.MIPS_ATLAS_CONFIG }}
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: List contents of resources directory
        run: |
          ls -l resources || dir resources || echo 'resources directory not found'
      - name: Set up Python, install, and run tests
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install, setup, and test
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e .
          uv pip install pytest
          python -m pytest -s
